serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  name: "oai-cm-sa"

#service type is fixed to clusterIP, it is only support for non multus interface (eth0)
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
