apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-decision
data:
  policy_decision.yaml: |
      decision_supi1:
        supi_imsi: "208950000000031"
        pcc_rules: 
          - steering-rule-primary
      decision_supi2:
        supi_imsi: "208950000000032"
        pcc_rules: 
          - steering-rule-secondary

