apiVersion: v1
kind: ConfigMap
metadata:
  name: pcc-rules
data:
  pcc_rules.yaml: |
    steering-rule-primary:
      flowInfos:
        - flowDescription: permit out ip from any to assigned
      precedence: 10
      refTcData:
        - steering-scenario-primary
    steering-rule-secondary:
      flowInfos:
        - flowDescription: permit out ip from any to assigned
      precedence: 10
      refTcData:
        - steering-scenario-secondary

