apiVersion: v1
kind: Service
metadata:
  name: external-amf #{{ .Chart.Name }}
  labels:
    {{- include "oai-amf.labels" . | nindent 4 }}
spec:
  type: LoadBalancer    # Change to LoadBalancer
  ports:
    - name: http
      port: {{ .Values.exposedPorts.sbi }}
      targetPort: {{ .Values.exposedPorts.sbi }}
      protocol: TCP
    - name: sctp
      port: {{ .Values.exposedPorts.sctp }}
      targetPort: {{ .Values.exposedPorts.sctp }}
      protocol: SCTP
  selector:
    {{- include "oai-amf.selectorLabels" . | nindent 4 }}

