apiVersion: v1
kind: Service
metadata:
  name: external-nrf #{{ .Chart.Name }}
  labels:
    {{- include "oai-nrf.labels" . | nindent 4 }}
spec:
  type: LoadBalancer    # Change to LoadBalancer
  ports:
    - name: http
      port: {{ .Values.exposedPorts.sbi }}
      targetPort: {{ .Values.exposedPorts.sbi }}
      protocol: TCP
  selector:
    {{- include "oai-nrf.selectorLabels" . | nindent 4 }}

