apiVersion: v1
kind: Service
metadata:
  name: external-smf #{{ .Chart.Name }}
  labels:
    {{- include "oai-smf.labels" . | nindent 4 }}
spec:
  type: LoadBalancer    # Change to LoadBalancer
  ports:
    - name: oai-smf
      # Port accessible outside cluster
      port: {{ .Values.exposedPorts.n4 }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.exposedPorts.n4 }}
      protocol: UDP
  selector:
    {{- include "oai-smf.selectorLabels" . | nindent 4 }}

